### ISSUE TITLE
TestCustomer API returning " ServiceId reqd in header"..

### ISSUE THREAD

**Issue by ramanrvg** [visa/SampleCode#36]
Tried TestCommunity first and it passed, but returned no values.
Then tried TestCustomer for getting and creating customer with test data, but it returned 

2017-02-21 12:13:38 INFO  VisaAPIClient:190 - ResponseBody: {
  "message" : "ServiceId is required in the header."
}

Although ServiceID is sent in the header in the same way TestCommunity is done, this response is returned.  Any clues?

=======
[TestNG] Running:
  C:\Users\Hp\AppData\Local\Temp\testng-eclipse--859123431\testng-customsuite.xml

2017-02-21 12:13:34 INFO  VisaAPIClient:204 - URI: https://sandbox.api.visa.com/vta/v3/communities/APP1038193/customers
2017-02-21 12:13:34 INFO  VisaAPIClient:205 - Create Customer Test
2017-02-21 12:13:35 INFO  VisaAPIClient:209 - RequestBody: {
  "customer" : {
    "cards" : [ {
      "address" : {
        "city" : "Toronto",
        "streetAddressOne" : "265 Queen Street W",
        "postalCode" : "M5V 1Z4",
        "streetAddressTwo" : null,
        "streetAddressThree" : null,
        "stateProvince" : "ON",
        "countryCode" : "CAN",
        "numericCountryCode" : "124"
      },
      "billCycleDay" : "7",
      "bin" : 431263,
      "cardEnrollmentDate" : "2017-02-21T06:43:34.475Z",
      "cardExpiryDate" : "112017",
      "cardNickName" : "My Card",
      "cardNumber" : "4957030103819340",
      "cardSecurityCode" : "304",
      "contactServiceOfferings" : [ {
        "contact" : {
          "contactNickName" : "testEmail",
          "contactType" : "Email",
          "contactValue" : "john@visa.com",
          "isVerified" : true,
          "lastUpdateDateTime" : "2017-02-21T06:43:34.475Z",
          "mobileCountryCode" : null,
          "mobileVerificationCode" : null,
          "mobileVerificationCodeDate" : "2017-02-21T06:43:34.475Z",
          "platform" : "None",
          "preferredEmailFormat" : "Html",
          "securityPhrase" : null,
          "status" : "Active"
        },
        "serviceOfferings" : [ {
          "isActive" : true,
          "offeringId" : "Threshold",
          "offeringProperties" : [ {
            "key" : "ThresholdAmount",
            "value" : "10"
          } ]
        }, {
          "isActive" : true,
          "offeringId" : "CrossBorder",
          "offeringProperties" : [ {
            "key" : "ThresholdAmount",
            "value" : "10"
          } ]
        }, {
          "isActive" : true,
          "offeringId" : "Declined",
          "offeringProperties" : [ {
            "key" : "ThresholdAmount",
            "value" : "10"
          } ]
        }, {
          "isActive" : true,
          "offeringId" : "CardNotPresent",
          "offeringProperties" : [ {
            "key" : "ThresholdAmount",
            "value" : "10"
          } ]
        } ]
      } ],
      "isActive" : true,
      "lastFour" : "9340",
      "nameOnCard" : "Migration",
      "paused" : false,
      "portfolioNum" : "001",
      "previousCardNumber" : null,
      "productId" : null,
      "productIdDescription" : "Credit",
      "productType" : "Credit",
      "productTypeExtendedCode" : "Credit",
      "rpin" : null
    } ],
    "communityCode" : "APP1038193",
    "contacts" : [ {
      "contactNickName" : "testEmail",
      "contactType" : "Email",
      "contactValue" : "john@visa.com",
      "isVerified" : true,
      "lastUpdateDateTime" : "2017-02-21T06:43:34.475Z",
      "mobileCountryCode" : null,
      "mobileVerificationCode" : null,
      "mobileVerificationCodeDate" : "2017-02-21T06:43:34.475Z",
      "platform" : "None",
      "preferredEmailFormat" : "Html",
      "securityPhrase" : null,
      "status" : "Active"
    } ],
    "customerEnrollmentDate" : "2017-02-21T06:43:34.475Z",
    "customerId" : "a1bb6fe1-ea64-4269-b29d-169aebd8780a",
    "firstName" : "James",
    "isActive" : true,
    "lastName" : "Bond",
    "preferredCountryCode" : "USA",
    "preferredCurrencyCode" : "USD",
    "preferredFuelAmount" : "75",
    "preferredLanguage" : "en-us",
    "preferredTimeZone" : "UTC-08:00",
    "preferredTipPercentage" : "15"
  }
}
2017-02-21 12:13:35 INFO  VisaAPIClient:113 - ServiceId:0ebd7267-515d-4e80-ae9f-4bc2cfdb0876
2017-02-21 12:13:35 INFO  VisaAPIClient:120 - Content-Type : application/json
2017-02-21 12:13:35 INFO  VisaAPIClient:120 - Accept : application/json
2017-02-21 12:13:35 INFO  VisaAPIClient:120 - Authorization : Basic Q1JCSUI1T1lISE9YSFRGWERSODQyMXQwOU1DUVh0U0xoekR5TU9QRUZWR1RjUjJoTToxTFN5dDgyQlBlUFIwM2xEYmtiUjUzV2Rxdzh3Mw==
2017-02-21 12:13:35 INFO  VisaAPIClient:120 - x-correlation-id : z0uP1B2fga_SC
2017-02-21 12:13:35 INFO  VisaAPIClient:120 - ServiceId : 0ebd7267-515d-4e80-ae9f-4bc2cfdb0876
2017-02-21 12:13:37 INFO  VisaAPIClient:177 - Response status : HTTP/1.1 400 Bad Request

2017-02-21 12:13:37 INFO  VisaAPIClient:179 - Response Headers: 

2017-02-21 12:13:37 INFO  VisaAPIClient:182 - X-SERVED-BY:l73c032
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - X-CORRELATION-ID:1487659417_321_72_l73c032_VDP_ARM
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - Cache-Control:no-cache ,no-cache, no-store, must-revalidate
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - Pragma:no-cache
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - Expires:-1 ,Thu, 01 Jan 1970 00:00:00 GMT
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - X-Powered-By:ASP.NET
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - X-APP-STATUS:400
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - X-Frame-Options:SAMEORIGIN
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - X-XSS-Protection:1; mode=block
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - X-Content-Type-Options:nosniff
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - Strict-Transport-Security:max-age=2592000;includeSubdomains
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - Content-Security-Policy-Report-Only:default-src 'self' https://*.v.me https://*.visa.com;script-src 'self' 'unsafe-inline' 'unsafe-eval'  https://*.visa.com https://*.v.me;img-src 'self' https://*.v.me https://*.visa.com https://*.unica.com https://ad.doubleclick.net;style-src 'self' 'unsafe-inline' https://*.visa.com;object-src  https://*.v.me https://*.visa.com data:;report-uri /logging/logCSPReport;
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - X-Content-Security-Policy-Report-Only:default-src 'self' https://*.v.me https://*.visa.com;script-src 'self' 'unsafe-inline' 'unsafe-eval'  https://*.visa.com https://*.v.me;img-src 'self' https://*.v.me https://*.visa.com https://*.unica.com https://ad.doubleclick.net;style-src 'self' 'unsafe-inline' https://*.visa.com;object-src  https://*.v.me https://*.visa.com data:;report-uri /logging/logCSPReport;
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - X-WebKit-CSP-Report-Only:default-src 'self' https://*.v.me https://*.visa.com;script-src 'self' 'unsafe-inline' 'unsafe-eval'  https://*.visa.com https://*.v.me;img-src 'self' https://*.v.me https://*.visa.com https://*.unica.com https://ad.doubleclick.net;style-src 'self' 'unsafe-inline' https://*.visa.com;object-src  https://*.v.me https://*.visa.com data:;report-uri /logging/logCSPReport;
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - Content-Type:application/json;charset=utf-8
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - Content-Language:en-US
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - Content-Length:50
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - X-Cnection:close
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - Date:Tue, 21 Feb 2017 06:43:37 GMT
2017-02-21 12:13:37 INFO  VisaAPIClient:182 - Connection:close
2017-02-21 12:13:37 INFO  VisaAPIClient:183 - 
 Response Body:
2017-02-21 12:13:37 INFO  VisaAPIClient:190 - ResponseBody: {
  "message" : "ServiceId is required in the header."
}
2017-02-21 12:13:37 INFO  VisaAPIClient:204 - URI: https://sandbox.api.visa.com/vta/v3/communities/APP1038193/customers/inquiry
2017-02-21 12:13:37 INFO  VisaAPIClient:205 - Search Customers Test
2017-02-21 12:13:37 INFO  VisaAPIClient:209 - RequestBody: {
  "communityCode" : "APP268953",
  "limit" : 5,
  "offset" : 5,
  "sortKey" : "desc",
  "sortOrder" : "desc",
  "status" : "Active"
}
2017-02-21 12:13:37 INFO  VisaAPIClient:113 - ServiceId:0ebd7267-515d-4e80-ae9f-4bc2cfdb0876
2017-02-21 12:13:37 INFO  VisaAPIClient:120 - Content-Type : application/json
2017-02-21 12:13:37 INFO  VisaAPIClient:120 - Accept : application/json
2017-02-21 12:13:37 INFO  VisaAPIClient:120 - Authorization : Basic Q1JCSUI1T1lISE9YSFRGWERSODQyMXQwOU1DUVh0U0xoekR5TU9QRUZWR1RjUjJoTToxTFN5dDgyQlBlUFIwM2xEYmtiUjUzV2Rxdzh3Mw==
2017-02-21 12:13:37 INFO  VisaAPIClient:120 - x-correlation-id : viYnvFbsvf_SC
2017-02-21 12:13:37 INFO  VisaAPIClient:120 - ServiceId : 0ebd7267-515d-4e80-ae9f-4bc2cfdb0876
2017-02-21 12:13:38 INFO  VisaAPIClient:177 - Response status : HTTP/1.1 400 Bad Request

2017-02-21 12:13:38 INFO  VisaAPIClient:179 - Response Headers: 

2017-02-21 12:13:38 INFO  VisaAPIClient:182 - X-SERVED-BY:l73c033
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - X-CORRELATION-ID:1487659418_323_76_l73c033_VDP_ARM
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - Cache-Control:no-cache ,no-cache, no-store, must-revalidate
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - Pragma:no-cache
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - Expires:-1 ,Thu, 01 Jan 1970 00:00:00 GMT
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - X-Powered-By:ASP.NET
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - X-APP-STATUS:400
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - X-Frame-Options:SAMEORIGIN
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - X-XSS-Protection:1; mode=block
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - X-Content-Type-Options:nosniff
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - Strict-Transport-Security:max-age=2592000;includeSubdomains
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - Content-Security-Policy-Report-Only:default-src 'self' https://*.v.me https://*.visa.com;script-src 'self' 'unsafe-inline' 'unsafe-eval'  https://*.visa.com https://*.v.me;img-src 'self' https://*.v.me https://*.visa.com https://*.unica.com https://ad.doubleclick.net;style-src 'self' 'unsafe-inline' https://*.visa.com;object-src  https://*.v.me https://*.visa.com data:;report-uri /logging/logCSPReport;
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - X-Content-Security-Policy-Report-Only:default-src 'self' https://*.v.me https://*.visa.com;script-src 'self' 'unsafe-inline' 'unsafe-eval'  https://*.visa.com https://*.v.me;img-src 'self' https://*.v.me https://*.visa.com https://*.unica.com https://ad.doubleclick.net;style-src 'self' 'unsafe-inline' https://*.visa.com;object-src  https://*.v.me https://*.visa.com data:;report-uri /logging/logCSPReport;
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - X-WebKit-CSP-Report-Only:default-src 'self' https://*.v.me https://*.visa.com;script-src 'self' 'unsafe-inline' 'unsafe-eval'  https://*.visa.com https://*.v.me;img-src 'self' https://*.v.me https://*.visa.com https://*.unica.com https://ad.doubleclick.net;style-src 'self' 'unsafe-inline' https://*.visa.com;object-src  https://*.v.me https://*.visa.com data:;report-uri /logging/logCSPReport;
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - Content-Type:application/json;charset=utf-8
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - Content-Language:en-US
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - Content-Length:50
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - X-Cnection:close
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - Date:Tue, 21 Feb 2017 06:43:38 GMT
2017-02-21 12:13:38 INFO  VisaAPIClient:182 - Connection:close
2017-02-21 12:13:38 INFO  VisaAPIClient:183 - 
 Response Body:
2017-02-21 12:13:38 INFO  VisaAPIClient:190 - ResponseBody: {
  "message" : "ServiceId is required in the header."
}
PASSED: setUp
FAILED: testGetCustomerDetails
java.lang.AssertionError: expected [201] but found [400]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at com.visa.vdp.vta.TestManageCustomers.testGetCustomerDetails(TestManageCustomers.java:183)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

FAILED: testSearchCustomerDetails
java.lang.AssertionError: expected [200] but found [400]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at com.visa.vdp.vta.TestManageCustomers.testSearchCustomerDetails(TestManageCustomers.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

===============================================
    Default test
    Tests run: 3, Failures: 2, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 3, Failures: 2, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.EmailableReporter2@1ed3c8d: 16 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@1f4c3: 15 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@16f77cc: 32 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@104e3b2: 78 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@4af82c: 67 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 32 ms

**Comment by ankeshanand** [comment]
Hi @ramanrvg, Thanks for reporting the issue. We are looking into why the API call failed, and will get back soon.

**Comment by ramanrvg** [comment]
Hi @ankeshanand please let me know if you need more details.  Pls reply asap.

**Comment by ramanrvg** [comment]
Hi, 
Is there any update? Also could you pls direct me to any other forum where I can get quick support.

**Comment by vivek241** [comment]
@ramanrvg - Apologies for the delay in response. Are you still facing this issue?
